import "../styles/style.css";
import Header from "@/components/Header";
import BgPokeball from "@/components/BgPokeball";
export const metadata = {
  title: "Pokemon App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-zinc-50">
        <BgPokeball />
        <Header />
        {children}
      </body>
    </html>
  );
}
